#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuttiFoody.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BaseDeDatosGrupoSWAT")]
	public partial class DBConnectDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertAlimento(Alimento instance);
    partial void UpdateAlimento(Alimento instance);
    partial void DeleteAlimento(Alimento instance);
    partial void InsertUsuario(Usuario instance);
    partial void UpdateUsuario(Usuario instance);
    partial void DeleteUsuario(Usuario instance);
    partial void InsertPropiedad(Propiedad instance);
    partial void UpdatePropiedad(Propiedad instance);
    partial void DeletePropiedad(Propiedad instance);
    partial void InsertReceta(Receta instance);
    partial void UpdateReceta(Receta instance);
    partial void DeleteReceta(Receta instance);
    partial void InsertTipoAlimento(TipoAlimento instance);
    partial void UpdateTipoAlimento(TipoAlimento instance);
    partial void DeleteTipoAlimento(TipoAlimento instance);
    #endregion
		
		public DBConnectDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBConnectDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)

		
		public DBConnectDataContext(string connection) : base(connection, mappingSource)
		{
			OnCreated();
		}

        public DBConnectDataContext() : base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BaseDeDatosGrupoSWATConnectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

        public DBConnectDataContext(System.Data.IDbConnection connection) : base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBConnectDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBConnectDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Alimento> Alimento
		{
			get
			{
				return this.GetTable<Alimento>();
			}
		}
		
		public System.Data.Linq.Table<Usuario> Usuario
		{
			get
			{
				return this.GetTable<Usuario>();
			}
		}
		
		public System.Data.Linq.Table<AlimentoPropiedad> AlimentoPropiedad
		{
			get
			{
				return this.GetTable<AlimentoPropiedad>();
			}
		}
		
		public System.Data.Linq.Table<Propiedad> Propiedad
		{
			get
			{
				return this.GetTable<Propiedad>();
			}
		}
		
		public System.Data.Linq.Table<Receta> Receta
		{
			get
			{
				return this.GetTable<Receta>();
			}
		}
		
		public System.Data.Linq.Table<RecetaAlimento> RecetaAlimento
		{
			get
			{
				return this.GetTable<RecetaAlimento>();
			}
		}
		
		public System.Data.Linq.Table<RecetaFavorita> RecetaFavorita
		{
			get
			{
				return this.GetTable<RecetaFavorita>();
			}
		}
		
		public System.Data.Linq.Table<RecetaUsuario> RecetaUsuario
		{
			get
			{
				return this.GetTable<RecetaUsuario>();
			}
		}
		
		public System.Data.Linq.Table<TipoAlimento> TipoAlimento
		{
			get
			{
				return this.GetTable<TipoAlimento>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Alimento")]
	public partial class Alimento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdAlimento;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private string _ArchivoImagen;
		
		private int _FKTipoAlimento;
		

		private System.Nullable<int> _Calorias;
		
		private System.Nullable<int> _Proteinas;
		
		private EntityRef<TipoAlimento> _TipoAlimento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdAlimentoChanging(int value);
    partial void OnIdAlimentoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnArchivoImagenChanging(string value);
    partial void OnArchivoImagenChanged();
    partial void OnFKTipoAlimentoChanging(int value);
    partial void OnFKTipoAlimentoChanged();

    partial void OnCaloriasChanging(System.Nullable<int> value);
    partial void OnCaloriasChanged();
    partial void OnProteinasChanging(System.Nullable<int> value);
    partial void OnProteinasChanged();
    #endregion
		
		public Alimento()
		{
			this._TipoAlimento = default(EntityRef<TipoAlimento>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdAlimento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdAlimento
		{
			get
			{
				return this._IdAlimento;
			}
			set
			{
				if ((this._IdAlimento != value))
				{
					this.OnIdAlimentoChanging(value);
					this.SendPropertyChanging();
					this._IdAlimento = value;
					this.SendPropertyChanged("IdAlimento");
					this.OnIdAlimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(400)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArchivoImagen", DbType="VarChar(200)")]
		public string ArchivoImagen
		{
			get
			{
				return this._ArchivoImagen;
			}
			set
			{
				if ((this._ArchivoImagen != value))
				{
					this.OnArchivoImagenChanging(value);
					this.SendPropertyChanging();
					this._ArchivoImagen = value;
					this.SendPropertyChanged("ArchivoImagen");
					this.OnArchivoImagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKTipoAlimento", DbType="Int NOT NULL")]
		public int FKTipoAlimento
		{
			get
			{
				return this._FKTipoAlimento;
			}
			set
			{
				if ((this._FKTipoAlimento != value))
				{
					if (this._TipoAlimento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKTipoAlimentoChanging(value);
					this.SendPropertyChanging();
					this._FKTipoAlimento = value;
					this.SendPropertyChanged("FKTipoAlimento");
					this.OnFKTipoAlimentoChanged();
				}
			}
		}
		

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Calorias", DbType="Int")]
		public System.Nullable<int> Calorias
		{
			get
			{
				return this._Calorias;
			}
			set
			{
				if ((this._Calorias != value))
				{
					this.OnCaloriasChanging(value);
					this.SendPropertyChanging();
					this._Calorias = value;
					this.SendPropertyChanged("Calorias");
					this.OnCaloriasChanged();
				}
			}
		}
		

		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Proteinas", DbType="Int")]
		public System.Nullable<int> Proteinas
		{
			get
			{
				return this._Proteinas;
			}
			set
			{
				if ((this._Proteinas != value))
				{
					this.OnProteinasChanging(value);
					this.SendPropertyChanging();
					this._Proteinas = value;
					this.SendPropertyChanged("Proteinas");
					this.OnProteinasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoAlimento_Alimento", Storage="_TipoAlimento", ThisKey="FKTipoAlimento", OtherKey="IdTipoAlimento", IsForeignKey=true)]
		public TipoAlimento TipoAlimento
		{
			get
			{
				return this._TipoAlimento.Entity;
			}
			set
			{
				TipoAlimento previousValue = this._TipoAlimento.Entity;
				if (((previousValue != value) 
							|| (this._TipoAlimento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TipoAlimento.Entity = null;
						previousValue.Alimento.Remove(this);
					}
					this._TipoAlimento.Entity = value;
					if ((value != null))
					{
						value.Alimento.Add(this);
						this._FKTipoAlimento = value.IdTipoAlimento;
					}
					else
					{
						this._FKTipoAlimento = default(int);
					}
					this.SendPropertyChanged("TipoAlimento");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuario")]
	public partial class Usuario : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

		
		private int _IdUsuario;
		
		private string _Nombre;
		
		private string _Correo;
		
		private string _Contraseña;
		
		private EntitySet<Receta> _Receta;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdUsuarioChanging(int value);
    partial void OnIdUsuarioChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnCorreoChanging(string value);
    partial void OnCorreoChanged();
    partial void OnContraseñaChanging(string value);
    partial void OnContraseñaChanged();
    #endregion
		
		public Usuario()
		{
			this._Receta = new EntitySet<Receta>(new Action<Receta>(this.attach_Receta), new Action<Receta>(this.detach_Receta));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this.OnIdUsuarioChanging(value);
					this.SendPropertyChanging();
					this._IdUsuario = value;
					this.SendPropertyChanged("IdUsuario");
					this.OnIdUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Correo", DbType="VarChar(50)")]
		public string Correo
		{
			get
			{
				return this._Correo;
			}
			set
			{
				if ((this._Correo != value))
				{
					this.OnCorreoChanging(value);
					this.SendPropertyChanging();
					this._Correo = value;
					this.SendPropertyChanged("Correo");
					this.OnCorreoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(50)")]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this.OnContraseñaChanging(value);
					this.SendPropertyChanging();
					this._Contraseña = value;
					this.SendPropertyChanged("Contraseña");
					this.OnContraseñaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Receta", Storage="_Receta", ThisKey="IdUsuario", OtherKey="FKUsuario")]
		public EntitySet<Receta> Receta
		{
			get
			{
				return this._Receta;
			}
			set
			{
				this._Receta.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Receta(Receta entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = this;
		}
		
		private void detach_Receta(Receta entity)
		{
			this.SendPropertyChanging();
			entity.Usuario = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlimentoPropiedad")]
	public partial class AlimentoPropiedad
	{
		
		private int _FKAlimento;
		
		private int _FKPropiedad;
		
		public AlimentoPropiedad()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKAlimento", DbType="Int NOT NULL")]
		public int FKAlimento
		{
			get
			{
				return this._FKAlimento;
			}
			set
			{
				if ((this._FKAlimento != value))
				{
					this._FKAlimento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKPropiedad", DbType="Int NOT NULL")]
		public int FKPropiedad
		{
			get
			{
				return this._FKPropiedad;
			}
			set
			{
				if ((this._FKPropiedad != value))
				{
					this._FKPropiedad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlimentoPropiedad")]
	public partial class AlimentoPropiedad
	{
		
		private int _FKAlimento;
		
		private int _FKPropiedad;
		
		public AlimentoPropiedad()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKAlimento", DbType="Int NOT NULL")]
		public int FKAlimento
		{
			get
			{
				return this._FKAlimento;
			}
			set
			{
				if ((this._FKAlimento != value))
				{
					this._FKAlimento = value;
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Propiedad")]
	public partial class Propiedad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPropiedad;
		
		private string _Nombre;
		
		private string _Descripcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPropiedadChanging(int value);
    partial void OnIdPropiedadChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public Propiedad()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPropiedad", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPropiedad
		{
			get
			{
				return this._IdPropiedad;
			}
			set
			{
				if ((this._IdPropiedad != value))
				{
					this.OnIdPropiedadChanging(value);
					this.SendPropertyChanging();
					this._IdPropiedad = value;
					this.SendPropertyChanged("IdPropiedad");
					this.OnIdPropiedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKPropiedad", DbType="Int NOT NULL")]
		public int FKPropiedad
		{
			get
			{
				return this._FKPropiedad;
			}
			set
			{
				if ((this._FKPropiedad != value))
				{
					this._FKPropiedad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Propiedad")]
	public partial class Propiedad : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPropiedad;
		
		private string _Nombre;
		
		private string _Descripcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPropiedadChanging(int value);
    partial void OnIdPropiedadChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    #endregion
		
		public Propiedad()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPropiedad", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPropiedad
		{
			get
			{
				return this._IdPropiedad;
			}
			set
			{
				if ((this._IdPropiedad != value))
				{
					this.OnIdPropiedadChanging(value);
					this.SendPropertyChanging();
					this._IdPropiedad = value;
					this.SendPropertyChanged("IdPropiedad");
					this.OnIdPropiedadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}

		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(300)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Receta")]
	public partial class Receta : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdReceta;
		
		private string _Nombre;
		
		private string _Descripcion;
		
		private string _PasosASeguir;
		
		private string _Tiempo;
		
		private int _FKUsuario;
		
		private System.Nullable<decimal> _CaloriasTotales;
		
		private string _ArchivoImagen;
		
		private EntityRef<Usuario> _Usuario;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdRecetaChanging(int value);
    partial void OnIdRecetaChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnPasosASeguirChanging(string value);
    partial void OnPasosASeguirChanged();
    partial void OnTiempoChanging(string value);
    partial void OnTiempoChanged();
    partial void OnFKUsuarioChanging(int value);
    partial void OnFKUsuarioChanged();
    partial void OnCaloriasTotalesChanging(System.Nullable<decimal> value);
    partial void OnCaloriasTotalesChanged();
    partial void OnArchivoImagenChanging(string value);
    partial void OnArchivoImagenChanged();
    #endregion
		
		public Receta()
		{
			this._Usuario = default(EntityRef<Usuario>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdReceta", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdReceta
		{
			get
			{
				return this._IdReceta;
			}
			set
			{
				if ((this._IdReceta != value))
				{
					this.OnIdRecetaChanging(value);
					this.SendPropertyChanging();
					this._IdReceta = value;
					this.SendPropertyChanged("IdReceta");
					this.OnIdRecetaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="VarChar(400)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasosASeguir", DbType="VarChar(1000)")]
		public string PasosASeguir
		{
			get
			{
				return this._PasosASeguir;
			}
			set
			{
				if ((this._PasosASeguir != value))
				{
					this.OnPasosASeguirChanging(value);
					this.SendPropertyChanging();
					this._PasosASeguir = value;
					this.SendPropertyChanged("PasosASeguir");
					this.OnPasosASeguirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tiempo", DbType="VarChar(50)")]
		public string Tiempo
		{
			get
			{
				return this._Tiempo;
			}
			set
			{
				if ((this._Tiempo != value))
				{
					this.OnTiempoChanging(value);
					this.SendPropertyChanging();
					this._Tiempo = value;
					this.SendPropertyChanged("Tiempo");
					this.OnTiempoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUsuario", DbType="Int NOT NULL")]
		public int FKUsuario
		{
			get
			{
				return this._FKUsuario;
			}
			set
			{
				if ((this._FKUsuario != value))
				{
					if (this._Usuario.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFKUsuarioChanging(value);
					this.SendPropertyChanging();
					this._FKUsuario = value;
					this.SendPropertyChanged("FKUsuario");
					this.OnFKUsuarioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaloriasTotales", DbType="Decimal(5,2)")]
		public System.Nullable<decimal> CaloriasTotales
		{
			get
			{
				return this._CaloriasTotales;
			}
			set
			{
				if ((this._CaloriasTotales != value))
				{
					this.OnCaloriasTotalesChanging(value);
					this.SendPropertyChanging();
					this._CaloriasTotales = value;
					this.SendPropertyChanged("CaloriasTotales");
					this.OnCaloriasTotalesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ArchivoImagen", DbType="VarChar(200)")]
		public string ArchivoImagen
		{
			get
			{
				return this._ArchivoImagen;
			}
			set
			{
				if ((this._ArchivoImagen != value))
				{
					this.OnArchivoImagenChanging(value);
					this.SendPropertyChanging();
					this._ArchivoImagen = value;
					this.SendPropertyChanged("ArchivoImagen");
					this.OnArchivoImagenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Usuario_Receta", Storage="_Usuario", ThisKey="FKUsuario", OtherKey="IdUsuario", IsForeignKey=true)]
		public Usuario Usuario
		{
			get
			{
				return this._Usuario.Entity;
			}
			set
			{
				Usuario previousValue = this._Usuario.Entity;
				if (((previousValue != value) 
							|| (this._Usuario.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Usuario.Entity = null;
						previousValue.Receta.Remove(this);
					}
					this._Usuario.Entity = value;
					if ((value != null))
					{
						value.Receta.Add(this);
						this._FKUsuario = value.IdUsuario;
					}
					else
					{
						this._FKUsuario = default(int);
					}
					this.SendPropertyChanged("Usuario");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RecetaAlimento")]
	public partial class RecetaAlimento
	{
		
		private System.Nullable<int> _FKAlimento;
		
		private System.Nullable<int> _FKReceta;
		
		private System.Nullable<int> _Cantidad;
		
		public RecetaAlimento()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKAlimento", DbType="Int")]
		public System.Nullable<int> FKAlimento
		{
			get
			{
				return this._FKAlimento;
			}
			set
			{
				if ((this._FKAlimento != value))
				{
					this._FKAlimento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKReceta", DbType="Int")]
		public System.Nullable<int> FKReceta
		{
			get
			{
				return this._FKReceta;
			}
			set
			{
				if ((this._FKReceta != value))
				{
					this._FKReceta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RecetaFavorita")]
	public partial class RecetaFavorita
	{
		
		private System.Nullable<int> _FKReceta;
		
		private System.Nullable<int> _FKUsuario;
		
		public RecetaFavorita()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKReceta", DbType="Int")]
		public System.Nullable<int> FKReceta
		{
			get
			{
				return this._FKReceta;
			}
			set
			{
				if ((this._FKReceta != value))
				{
					this._FKReceta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUsuario", DbType="Int")]
		public System.Nullable<int> FKUsuario
		{
			get
			{
				return this._FKUsuario;
			}
			set
			{
				if ((this._FKUsuario != value))
				{
					this._FKUsuario = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.RecetaUsuario")]
	public partial class RecetaUsuario
	{
		
		private System.Nullable<int> _FKReceta;
		
		private System.Nullable<int> _FKUsuario;
		
		public RecetaUsuario()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKReceta", DbType="Int")]
		public System.Nullable<int> FKReceta
		{
			get
			{
				return this._FKReceta;
			}
			set
			{
				if ((this._FKReceta != value))
				{
					this._FKReceta = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FKUsuario", DbType="Int")]
		public System.Nullable<int> FKUsuario
		{
			get
			{
				return this._FKUsuario;
			}
			set
			{
				if ((this._FKUsuario != value))
				{
					this._FKUsuario = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TipoAlimento")]
	public partial class TipoAlimento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdTipoAlimento;
		
		private string _Nombre;
		
		private EntitySet<Alimento> _Alimento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdTipoAlimentoChanging(int value);
    partial void OnIdTipoAlimentoChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    #endregion
		
		public TipoAlimento()
		{
			this._Alimento = new EntitySet<Alimento>(new Action<Alimento>(this.attach_Alimento), new Action<Alimento>(this.detach_Alimento));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdTipoAlimento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdTipoAlimento
		{
			get
			{
				return this._IdTipoAlimento;
			}
			set
			{
				if ((this._IdTipoAlimento != value))
				{
					this.OnIdTipoAlimentoChanging(value);
					this.SendPropertyChanging();
					this._IdTipoAlimento = value;
					this.SendPropertyChanged("IdTipoAlimento");
					this.OnIdTipoAlimentoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TipoAlimento_Alimento", Storage="_Alimento", ThisKey="IdTipoAlimento", OtherKey="FKTipoAlimento")]
		public EntitySet<Alimento> Alimento
		{
			get
			{
				return this._Alimento;
			}
			set
			{
				this._Alimento.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Alimento(Alimento entity)
		{
			this.SendPropertyChanging();
			entity.TipoAlimento = this;
		}
		
		private void detach_Alimento(Alimento entity)
		{
			this.SendPropertyChanging();
			entity.TipoAlimento = null;
		}
	}
}
#endregion