<?xml version="1.0" encoding="utf-8"?><Database Name="BaseDeDatosGrupoSWAT" Class="DBConnectDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Alimento" Member="Alimento">
    <Type Name="Alimento">
      <Column Name="IdAlimento" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="Imagen" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ArchivoImagen" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="FKTipoAlimento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Calorias" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Proteinas" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Alimento_AlimentoPropiedad" Member="AlimentoPropiedad" ThisKey="IdAlimento" OtherKey="FKAlimento" Type="AlimentoPropiedad" />
      <Association Name="Alimento_RecetaAlimento" Member="RecetaAlimento" ThisKey="IdAlimento" OtherKey="FKAlimento" Type="RecetaAlimento" />
      <Association Name="TipoAlimento_Alimento" Member="TipoAlimento" ThisKey="FKTipoAlimento" OtherKey="IdTipoAlimento" Type="TipoAlimento" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Usuario" Member="Usuario">
    <Type Name="Usuario">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Contraseña" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Usuario_Receta" Member="Receta" ThisKey="IdUsuario" OtherKey="FKUsuario" Type="Receta" />
      <Association Name="Usuario_RecetaFavorita" Member="RecetaFavorita" ThisKey="IdUsuario" OtherKey="FKUsuario" Type="RecetaFavorita" />
      <Association Name="Usuario_RecetaUsuario" Member="RecetaUsuario" ThisKey="IdUsuario" OtherKey="FKUsuario" Type="RecetaUsuario" />
    </Type>
  </Table>
  <Table Name="dbo.AlimentoPropiedad" Member="AlimentoPropiedad">
    <Type Name="AlimentoPropiedad">
      <Column Name="FKAlimento" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FKPropiedad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Alimento_AlimentoPropiedad" Member="Alimento" ThisKey="FKAlimento" OtherKey="IdAlimento" Type="Alimento" IsForeignKey="true" />
      <Association Name="Propiedad_AlimentoPropiedad" Member="Propiedad" ThisKey="FKPropiedad" OtherKey="IdPropiedad" Type="Propiedad" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Propiedad" Member="Propiedad">
    <Type Name="Propiedad">
      <Column Name="IdPropiedad" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(300)" CanBeNull="true" />
      <Association Name="Propiedad_AlimentoPropiedad" Member="AlimentoPropiedad" ThisKey="IdPropiedad" OtherKey="FKPropiedad" Type="AlimentoPropiedad" />
    </Type>
  </Table>
  <Table Name="dbo.Receta" Member="Receta">
    <Type Name="Receta">
      <Column Name="IdReceta" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Descripcion" Type="System.String" DbType="VarChar(400)" CanBeNull="true" />
      <Column Name="PasosASeguir" Type="System.String" DbType="VarChar(1000)" CanBeNull="true" />
      <Column Name="Tiempo" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FKUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CaloriasTotales" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="ArchivoImagen" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Receta_RecetaAlimento" Member="RecetaAlimento" ThisKey="IdReceta" OtherKey="FKReceta" Type="RecetaAlimento" />
      <Association Name="Receta_RecetaFavorita" Member="RecetaFavorita" ThisKey="IdReceta" OtherKey="FKReceta" Type="RecetaFavorita" />
      <Association Name="Receta_RecetaUsuario" Member="RecetaUsuario" ThisKey="IdReceta" OtherKey="FKReceta" Type="RecetaUsuario" />
      <Association Name="Usuario_Receta" Member="Usuario" ThisKey="FKUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RecetaAlimento" Member="RecetaAlimento">
    <Type Name="RecetaAlimento">
      <Column Name="FKAlimento" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FKReceta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Alimento_RecetaAlimento" Member="Alimento" ThisKey="FKAlimento" OtherKey="IdAlimento" Type="Alimento" IsForeignKey="true" />
      <Association Name="Receta_RecetaAlimento" Member="Receta" ThisKey="FKReceta" OtherKey="IdReceta" Type="Receta" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RecetaFavorita" Member="RecetaFavorita">
    <Type Name="RecetaFavorita">
      <Column Name="FKReceta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FKUsuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Receta_RecetaFavorita" Member="Receta" ThisKey="FKReceta" OtherKey="IdReceta" Type="Receta" IsForeignKey="true" />
      <Association Name="Usuario_RecetaFavorita" Member="Usuario" ThisKey="FKUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.RecetaUsuario" Member="RecetaUsuario">
    <Type Name="RecetaUsuario">
      <Column Name="FKReceta" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FKUsuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Receta_RecetaUsuario" Member="Receta" ThisKey="FKReceta" OtherKey="IdReceta" Type="Receta" IsForeignKey="true" />
      <Association Name="Usuario_RecetaUsuario" Member="Usuario" ThisKey="FKUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TipoAlimento" Member="TipoAlimento">
    <Type Name="TipoAlimento">
      <Column Name="IdTipoAlimento" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TipoAlimento_Alimento" Member="Alimento" ThisKey="IdTipoAlimento" OtherKey="FKTipoAlimento" Type="Alimento" />
    </Type>
  </Table>
</Database>